#cloud-config
# See examples: https://github.com/canonical/cloud-init/tree/main/doc/examples

# Hostname is automatically replaced with virt-cloud-init.sh script upon execution
hostname: default-vm
locale: en_US.UTF-8

# disable ssh access as root.
disable_root: true

# if you want to allow SSH with password, set this to true
ssh_pwauth: true

# users[0] (the first user in users) overrides the user directive.
users:
  - name: kube
    gecos: Kube use
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, adm
    shell: /bin/bash
    lock_passwd: false
    ## Generate with:
    # $ mkpasswd --method=SHA-512 --rounds=4096
    hashed_passwd: |
      $6$rounds=4096$XXXXXXXXXXXXX...........
    ssh_authorized_keys:
      - "ssh-ed25519 AAAA.........."

# Env variables
write_files:
  - path: /etc/netplan/99-network.yaml
    content: |
      network:
        version: 2
        ethernets:
          <INTERFACE>:
            dhcp4: <DHCP>
            dhcp6: false
            <STATIC>

# list of packages to install after the VM comes up
package_upgrade: true
package_reboot_if_required: true
package_update: true
packages:
  - vim
  - curl

runcmd:
  - echo "Hello World!"
  - chmod 600 /etc/netplan/99-network.yaml
  - netplan apply


# written to /var/log/cloud-init-output.log
final_message: "The system is finally up, after $UPTIME seconds"
